### ISSUE TITLE
didi dataset

### ISSUE THREAD

**Issue by dryjins** [uctb/UCTB#12]
Hi! Thanks for UCTB.

I have an issue on downloading DiDi data from the document. It seems the links are dead.
http://47.94.208.154/md_file/static/MakeDatasetDiDi.html?highlight=didi

Is there any links for this dataset?

**Comment by Liyue-Chen** [comment]
Hi~ 
Thanks for your attention. DiDi GAIA project has updated the open-source policy. I revisit the previous access link and the GAIA team suggests contacting them via `gaia@didiglobal.com`. Maybe you could email them to get the data license.
