### ISSUE TITLE
STMeta QuickStart has no attribute LM

### ISSUE THREAD

**Issue by Jinmengyu6** [uctb/UCTB#5]
I don't fine the attribute LM in data_loader.py, but it was used in STMeta. and can't run success
the code as below

STMeta_Obj = STMeta(closeness_len=data_loader.closeness_len,
                    period_len=data_loader.period_len,
                    trend_len=data_loader.trend_len,
                    num_node=data_loader.station_number,
                    num_graph=data_loader.LM.shape[0],
                    external_dim=data_loader.external_dim)

**Comment by Liyue-Chen** [comment]
Hi,

Thanks for your attention. This error occur because we change graph generating way in UCTB and we didn't update STMeta QuickStart code in time.

We have updated STMeta QuickStart code, please pull latest code.

Thanks.

**Comment by Liyue-Chen** [comment]
> I don't fine the attribute LM in data_loader.py, but it was used in STMeta. and can't run success
> the code as below
> 
> STMeta_Obj = STMeta(closeness_len=data_loader.closeness_len,
> period_len=data_loader.period_len,
> trend_len=data_loader.trend_len,
> num_node=data_loader.station_number,
> num_graph=data_loader.LM.shape[0],
> external_dim=data_loader.external_dim)

Hi,

Thanks for your attention. This error occur because we change graph generating way in UCTB and we didn't update STMeta QuickStart code in time.

We have updated STMeta QuickStart code, please pull latest code.

Thanks.

**Comment by QAQTATQAQTAT** [comment]
I can‘t run success the code and error as below：

code：
data_loader = NodeTrafficLoader(dataset='Bike', city='NYC', graph='Correlation',
                                closeness_len=6, period_len=7, trend_len=4, normalize=True)
error：
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接

maybe it happen because I don‘t have file  “NYCBike”？

**Comment by Liyue-Chen** [comment]
> I can‘t run success the code and error as below：
> 
> code：
> data_loader = NodeTrafficLoader(dataset='Bike', city='NYC', graph='Correlation',
> closeness_len=6, period_len=7, trend_len=4, normalize=True)
> error：
> ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接
> 
> maybe it happen because I don‘t have file “NYCBike”？

Hi,

Thanks for your attention. This error occurs because the data weren't downloaded correctly. You can visit our BIKE datasets at the following repo (https://github.com/Di-Chai/UCTB_Data).

And then move the data into the `data` directory in the root directory that your UCTB installed in. (e.g. XXX\Python\Python36\Lib\site-packages\UCTB\data)

Thanks.

**Comment by QAQTATQAQTAT** [comment]
Oh,Thanks for your reply immediately!

I download the file and move this file into the right location,but when I run it again,it occurs a new error.

error:Found C:\Users\DELL\AppData\Roaming\Python\Python36\site-packages\UCTB\data\Bike_NYC.tar.gz
not a gzip file

I can't use 7-zip to change .gz file to .gzip file.

**Comment by Liyue-Chen** [comment]
> Oh,Thanks for your reply immediately!
> 
> I download the file and move this file into the right location,but when I run it again,it occurs a new error.
> 
> error:Found C:\Users\DELL\AppData\Roaming\Python\Python36\site-packages\UCTB\data\Bike_NYC.tar.gz
> not a gzip file
> 
> I can't use 7-zip to change .gz file to .gzip file.

Just use 7-zip to transform the `*.tar.gz` files to `*.pkl` and move them into the right place.

**Comment by QAQTATQAQTAT** [comment]
I tried many times with 7-zip, but it can't convert to *.pkL file.It would appear the error message when I used 7-zip to extract the file at the second step.I also tried many of the other approaches I have seen online,but they don't work.

If it 's convenient for you, can you directly send the *.pkl file to taoguo19@mails.jlu.edu.cn.

**Comment by QAQTATQAQTAT** [comment]
I couldn't download some data successfully,Like ST-ResNet.Is there a solution?
![image](https://user-images.githubusercontent.com/37134602/113531848-6c86c180-95fc-11eb-9c6c-627a6b68ccb1.png)
